apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kato-bot.name" . }}-groups
  labels:
    {{- include "kato-bot.labels" . | nindent 4 }}
data:
  groups.yaml: |
    groups:
    {{- range .Values.groups }}
      - name: {{ .name | quote }}
        cluster: {{ .cluster | quote }}
        {{- if .concurrency }}
        concurrency: {{ .concurrency }}
        {{- end }}
        {{- if .summary }}
        summary: true
        {{- end }}
        usecases:
        {{- range .usecases }}
          - usecase: {{ .usecase | quote }}
            targets:
            {{- range .targets }}
              - {{ toJson . }}
            {{- end }}
        {{- end }}
    {{- end }}
